// memo-ui-react/src/components/home/ProfileCard.jsx
import {Avatar, Card, Chip, Skeleton, Typography, useColorScheme} from "@mui/joy";
import avatarWhite from "@/assets/img/megalobox-white.webp";
import avatarBlack from "@/assets/img/megalobox.webp";
import {useState} from "react";

export const ProfileCard = ({
                                name = "",
                                quote = "",
                                quoteName = ""
                            }) => {
    const themeMode = useColorScheme();
    const [loading, setLoading] = useState(false);

    return (
        <>
            <div className={`flex flex-col gap-4`}>
                <div className={`w-full flex flex-row justify-start content-center gap-5`}>
                    <Avatar
                        color="neutral"
                        size="lg"
                        variant="plain"
                        src={`${loading ? '' : `${themeMode.colorScheme === "dark" ? avatarWhite : avatarBlack}`}`}
                        sx={{
                            width: '4rem',
                            height: '4rem'
                        }}
                    >
                        <Skeleton loading={loading}/>
                        {(name !== null && name !== "") && name.charAt(0).toUpperCase()}
                    </Avatar>
                    {(name !== null && name !== "") &&
                        <Typography className={`flex justify-center content-center`} level="title-lg">
                            <span className={`text-xl font-bold`}>
                                {name.charAt(0).toUpperCase()}
                            </span>
                            <span className={`text-xs font-bold`}>
                                {name.substring(1, name.length).toUpperCase()}
                            </span>
                        </Typography>}
                </div>
                <div className={`w-full flex flex-row justify-start content-center gap-1`}>
                    <Chip
                        color="success"
                        variant="soft"
                        size="sm"
                    >
                        <span className={'font-bold'}>GAMER</span>
                    </Chip>
                    <Chip
                        color="primary"
                        variant="soft"
                        size="sm"
                    >
                        <span className={'font-bold'}>DEVELOPER</span>
                    </Chip>
                </div>
                {(quote !== null && quote !== "") && <Card sx={{
                    boxShadow: 'lg',
                }}
                                                           color="neutral" variant="soft">
                    <Typography level="title-md" color="neutral">
                        <span className={`font-bold block`}>
                            {quote}
                        </span>
                        {quoteName !== null && <span>
                            <i> - {quoteName} </i>
                        </span>}
                    </Typography>
                </Card>}
            </div>
        </>
    )
}

// front/src/components/ProfileCard.vue
<script setup>
import avatarWhite from "@/assets/img/megalobox-white.png";
import avatarBlack from "@/assets/img/megalobox.png";
import {nextTick, ref} from "vue";

const props = defineProps({
  theme: {
    type: String,
    default: () => "dark",
  },
  name: {
    type: String,
  },
  quote: {
    type: String,
  },
  quoteName: {
    type: String,
  }
});
</script>

<template>
  <div style="display: flex; width: 100%"
       class="flex-direction-row
                align-center justify-start">
    <VaAvatar v-show="props.theme === 'dark'"
              class="mr-3"
              size="large"
              :src="avatarWhite"
    />
    <VaAvatar v-show="props.theme === 'light'"
              class="mr-3"
              size="large"
              :src="avatarBlack"
    />
    <div v-if="props.name !== null"
        style="font-size: 0.9rem"
         class="ml-3 va-title">
      <span style="font-size: x-large">
        {{ props.name.charAt(0) }}
      </span>{{ props.name.substring(1, props.name.length) }}
    </div>
    <VaSkeleton v-else variant="text" animation="wave" style="font-size: 0.9rem" class="ml-3 va-title"/>
  </div>
  <div class="mt-3">
    <VaBadge
        text="A Gamer"
        color="success"
        class="mr-2"
    />
    <VaBadge
        text="A Developer"
        color="primary"
    />
  </div>
  <div class="mt-3" v-if="quote !== null">
    <blockquote class="va-blockquote va-text-block">
      <p class="va-text-bold">
       {{ props.quote }}
      </p>
      <p v-if="quoteName !== null">
        <i>- {{ props.quoteName }}</i>
      </p>
    </blockquote>
  </div>
</template>

<style scoped>

</style>
