// memo-ui-react/src/components/home/BlogIndex.jsx
import {useSelector} from "react-redux";
import {selectBlogContent} from "@/assets/js/data/reducer/blog_content_slice.js";
import {List, ListItem, ListItemButton, ListItemDecorator, Typography} from "@mui/joy";
import {useEffect, useState} from "react";
import {marked} from "marked";
import {smooth_scroll} from "@/assets/js/utils/scroll.js";

export const BlogIndex = () => {
    const content = useSelector(selectBlogContent);
    const [maxTitle, setMaxTitle] = useState(null);
    const [blogIndex, setBlogIndex] = useState([]);
    const [max, setMax] = useState(1);
    const [min] = useState(6);

    useEffect(() => {
        indexOfBlog(content);
        console.log(blogIndex)
    }, [content]);

    useEffect(() => {
        setMax(maxTitle);
    }, [maxTitle]);

    useEffect(() => {
        const render = document.querySelector("#render");
        for (let i = min; i >= max; i--)
            findHeading(render, i);
    }, [blogIndex, max, min]);

    const findHeading = async (render, level) => {
        const levelHeading = blogIndex.filter(el => {
            return el.tag === level;
        });
        if (levelHeading.length === 0) {
            return;
        }
        render.querySelectorAll(`h${level}`).forEach((el, i) => {
            el.setAttribute("id", `blog-index-${levelHeading[i].id}`);
        });
    };

    const indexOfBlog = (content) => {
        if (content !== null) {
            let anchor = 0;
            let rendererMD = new marked.Renderer();
            // eslint-disable-next-line no-unused-vars
            rendererMD.heading = (text, level, _) => {
                if (maxTitle === null || level < maxTitle) {
                    setMaxTitle(level);
                }
                anchor += 1;

                let isExists = false;
                for (let i = 0; i < blogIndex.length; i++) {
                    if (blogIndex[i].id === anchor) {
                        isExists = true;
                        break;
                    }
                }

                if (!isExists) {
                    let list = blogIndex;
                    list.push(
                        {
                            'id': anchor,
                            'tag': level,
                            'text': text
                        });
                    setBlogIndex(list);
                }
                return `<h${level}>${text}</h${level}>`;
            }

            marked.setOptions({
                renderer: rendererMD,
                pedantic: false,
                gfm: true,
                tables: true,
                breaks: false,
                sanitize: false,
                smartLists: true,
                smartypants: false,
                xhtml: false
            });
            marked(content);
        }
    }

    return (
        <>
            <List
                className={'select-none'}
                size="lg"
                color="primary"
                variant="plain"
                sx={{
                    "--List-gap": "5px"
                }}
            >
                <Typography level="h4" color="neutral">
                    <span style={{
                        fontSize: 'x-large'
                    }}>I</span>ndex
                </Typography>
                {
                    blogIndex.map((item, i) => (
                        <ListItem key={i} className={`cursor-pointer select-none`}
                                  style={{
                                      marginLeft: `${((item.tag - maxTitle) * 10)}px`
                                  }}
                                  sx={{
                                      width: '100%'
                                  }}>
                            <ListItemButton
                                onClick={() => smooth_scroll(`blog-index-${item.id}`)}
                                color={"primary"}
                                className={'flex flex-row justify-start'} sx={{
                                borderRadius: '6px'
                            }}>
                                <p className={`text-base font-bold`}>{item.text}</p>
                            </ListItemButton>
                        </ListItem>
                    ))
                }
            </List>
        </>
    )
}

// front/src/components/home/BlogIndex.vue
<script setup>
import {nextTick, ref, watch} from "vue";

const props = defineProps({
  theme: {
    type: String,
    default: () => "dark",
  },
  blogIndex: {
    type: Array,
    default: () => null
  },
  maxTag: {
    type: Number,
    default: 1
  }
});


const max = ref(props.maxTag);
const min = ref(6);

const findHeading = async (render, level) => {
  const levelHeading = props.blogIndex.filter(el => {
    return el.tag === level;
  });
  if (levelHeading.length === 0) {
    return;
  }
  render.querySelectorAll(`h${level}`).forEach((el, i) => {
    el.setAttribute("id", `blog-index-${levelHeading[i].id}`);
  });
};

nextTick(() => {
  watch(() => props.blogIndex, (index) => {
    if (index !== null && index.length > 0) {
      const render = document.querySelector("#render");
      for (let i = min.value; i >= max.value; i--)
        findHeading(render, i);
    }
  });
});
</script>

<template>
  <div v-if="props.blogIndex !== null && props.blogIndex.length > 0">
    <VaDivider class="mt-4 mb-3"/>
    <VaList>
      <VaListLabel
          style="font-size: 1rem; text-align: left"
          color="secondary"
      >
        <span style="font-size: x-large">I</span>ndex
      </VaListLabel>

      <VaScrollContainer
          style="max-height: 150px"
          color="primary"
          vertical
      >
        <VaListItem
            v-for="(item, index) in blogIndex"
            :key="index"
            :href="`#blog-index-${item.id}`"
            :style="{marginLeft: `${((item.tag - maxTag) * 10)}px`}"
            class="list pointer"
            :class="{
          'list-dark-bg': props.theme === 'dark',
          'list-light-bg': props.theme === 'light',
          'list-light': props.theme === 'light',
        }"
        >
          <VaListSeparator spaced/>
          <VaListItemSection class="ml-3">
            <VaListItemLabel
                :lines="2"
                caption
                class="va-text-bold list-text"
                style="font-size: 0.9rem;">
              {{ item.text }}
            </VaListItemLabel>
          </VaListItemSection>
        </VaListItem>
      </VaScrollContainer>
    </VaList>
  </div>
</template>

<style scoped>
@import "@/assets/css/common.css";
</style>
